version: "3"

services:
  jupyterhub:
    user: "0:0"
    ports:
      - "8000:8000"
    restart: always
    build: jupyterhub
    image: aabadie/iot-lab-jupyterhub
    container_name: jupyterhub
    networks:
      default:
        aliases:
          - ${DOCKER_NETWORK_NAME}
    environment:
      - DOCKER_NETWORK_NAME
      - JUPYTERHUB_USERS_DIR
      - JUPYTERLAB_DOCKER_IMAGE
      - JUPYTERLAB_USERNAME
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "${JUPYTERHUB_USERS_DIR}:/srv/jupyterhub/users"
    command: >
      jupyterhub -f /srv/jupyterhub/iotlab_config.py

  jupyterlab:
    build: jupyterlab
    image: aabadie/iot-lab-jupyterlab
    container_name: jupyterlab-none
    command: echo

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
