version: "3"

services:
  jupyterhub-iotlab:
    user: 0:0
    ports:
      - 8000:8000
    build:
      context: jupyterhub
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    image: fitiotlab/iot-lab-jupyterhub
    container_name: jupyterhub-iotlab
    environment:
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - JUPYTERHUB_INSTANCE=iotlab
      - JUPYTERHUB_TRAINING_DIR
      - JUPYTERHUB_CRYPT_KEY
      - JUPYTERLAB_DOCKER_IMAGE
      - JUPYTERLAB_USERNAME
      - IOTLAB_API_URL
      - IOTLAB_SITES
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # Bind local services with Jupyterhub services inside container
      - ./jupyterhub/services:/srv/jupyterhub/services

    command: >
      jupyterhub -f /srv/jupyterhub/iotlab_config.py --log-level=${JUPYTERHUB_DEBUG_LEVEL}
    restart: on-failure

  jupyterhub-mooc:
    user: 0:0
    ports:
      - 8800:8000
    build:
      context: jupyterhub
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    image: fitiotlab/iot-lab-jupyterhub
    container_name: jupyterhub-mooc
    environment:
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - JUPYTERHUB_INSTANCE=mooc
      - JUPYTERHUB_TRAINING_DIR
      - JUPYTERHUB_CRYPT_KEY
      - JUPYTERLAB_DOCKER_IMAGE
      - JUPYTERLAB_USERNAME
      - IOTLAB_API_URL
      - IOTLAB_SITES
      - IOTLAB_ADMIN_USER
      - IOTLAB_ADMIN_PASSWORD
      - LTI_KEY
      - LTI_SECRET
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # Bind local services with Jupyterhub services inside container
      - ./jupyterhub/services:/srv/jupyterhub/services

    command: >
      jupyterhub -f /srv/jupyterhub/iotlab_config.py --log-level=${JUPYTERHUB_DEBUG_LEVEL}
    restart: on-failure

  jupyterlab-base:
    build:
      context: jupyterlab-base
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    image: fitiotlab/iot-lab-jupyterlab-base
    container_name: jupyterlab-base-none
    command: echo

  jupyterlab:
    build:
      context: jupyterlab
    image: fitiotlab/iot-lab-jupyterlab
    container_name: jupyterlab-none
    command: echo
